"""Generate responsive copies; never alter original project screenshots.
Run after adding/changing screenshots: python scripts/optimize-images.py
Requires Pillow. Generated media and imageVariants.js are committed, so deployment
and the regular Node build do not require Python or Pillow.
"""
from pathlib import Path
import hashlib
import json
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
media = ROOT / 'public' / 'media'
social = ROOT / 'public' / 'social'
media.mkdir(parents=True, exist_ok=True)
social.mkdir(parents=True, exist_ok=True)
imports, entries = [], []
original_total, thumbnail_total = 0, 0
for index, source in enumerate(sorted((ROOT / 'src' / 'assets').glob('*.webp'))):
    image = ImageOps.exif_transpose(Image.open(source)).convert('RGB')
    width, height = image.size
    digest = hashlib.sha256(source.read_bytes()).hexdigest()[:10]
    sizes = sorted(set(min(width, size) for size in (480, 960, 1440)))
    copies = []
    for size in sizes:
        filename = f'{source.stem}-{digest}-{size}.webp'
        target = media / filename
        resized = image.resize((size, round(height * size / width)), Image.Resampling.LANCZOS)
        resized.save(target, 'WEBP', quality=85, method=6)
        copies.append((size, f'/media/{filename}'))
    # JPEG is widely supported by social crawlers. Preserve the screenshot's framing.
    social_image = image.copy()
    social_image.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
    social_name = f'{source.stem}-{digest}.jpg'
    social_image.save(social / social_name, 'JPEG', quality=88, optimize=True)
    if source.stem == 'multisite':
        social_image.save(social / 'portfolio.jpg', 'JPEG', quality=88, optimize=True)
    imports.append(f'import image{index} from {json.dumps("../assets/" + source.name)};')
    medium = next((url for size, url in copies if size >= min(960, width)), copies[-1][1])
    entry = {'sourceFile': source.name, 'sourceHash': digest, 'width': width, 'height': height, 'medium': medium, 'large': copies[-1][1],
             'srcSet': ', '.join(f'{url} {size}w' for size, url in copies), 'social': f'/social/{social_name}'}
    entries.append(f'  [image{index}]: {json.dumps(entry)},')
    original_total += source.stat().st_size
    thumbnail_total += (ROOT / 'public' / copies[0][1].lstrip('/')).stat().st_size

(ROOT / 'src' / 'data' / 'imageVariants.js').write_text(
    '// Generated by scripts/optimize-images.py; original screenshots remain unchanged.\n'
    + '\n'.join(imports) + '\n\nexport default {\n' + '\n'.join(entries) + '\n};\n', encoding='utf-8')
print(f'{len(entries)} images optimized. Original total: {original_total:,} bytes; smallest variants: {thumbnail_total:,} bytes.')

icon = Image.open(ROOT / 'public' / 'favicon.png').convert('RGBA')
for size in (32, 180, 192, 512):
    icon.resize((size, size), Image.Resampling.LANCZOS).save(ROOT / 'public' / f'icon-{size}.png', optimize=True)
